import { chmod, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const outfile = resolve(root, "skills/desktop-computer-use/scripts/dcu.mjs");
const licenseReport = resolve(root, "skills/desktop-computer-use/references/THIRD_PARTY_LICENSES.md");
const licenseFileNames = new Set(["LICENSE", "LICENSE.MD", "LICENSE.TXT", "COPYING", "NOTICE"]);
await mkdir(dirname(outfile), { recursive: true });
const buildResult = await build({
  entryPoints: [resolve(root, "src/cli.ts")],
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  outfile,
  legalComments: "eof",
  sourcemap: false,
  metafile: true,
  banner: { js: "#!/usr/bin/env node\n" }
});
const current = await readFile(outfile, "utf8");
if (!current.startsWith("#!/usr/bin/env node")) throw new Error("Skill bundle did not contain the node launcher");
await writeFile(outfile, current, { encoding: "utf8", mode: 0o755 });
await chmod(outfile, 0o755);

function packageIdentityFromInput(input) {
  const normalized = input.replaceAll("\\", "/");
  const match = normalized.match(/(?:^|\/)node_modules\/(.+)$/);
  if (!match) return undefined;
  const markerIndex = match.index ?? 0;
  const packagePath = match[1];
  const parts = packagePath.split("/").filter(Boolean);
  if (parts.length === 0) return undefined;
  const packageName = parts[0].startsWith("@") ? parts.slice(0, 2).join("/") : parts[0];
  const packageRoot = resolve(root, normalized.slice(0, markerIndex), "node_modules", packageName);
  return packageName ? { packageName, packageRoot } : undefined;
}

async function packageMetadata({ packageName, packageRoot }) {
  const packageJsonPath = join(packageRoot, "package.json");
  const packageJson = JSON.parse(await readFile(packageJsonPath, "utf8"));
  const entries = await readdir(packageRoot, { withFileTypes: true });
  const licenseEntry = entries.find(entry => entry.isFile() && licenseFileNames.has(entry.name.toUpperCase()));
  const licensePath = licenseEntry ? join(packageRoot, licenseEntry.name) : undefined;
  return {
    packageName,
    version: String(packageJson.version ?? "unknown"),
    license: packageJson.license ?? packageJson.licenses ?? "unknown",
    licensePath,
    licenseText: licensePath ? await readFile(licensePath, "utf8") : undefined
  };
}

const packageIdentities = new Map();
for (const input of Object.keys(buildResult.metafile?.inputs ?? {})) {
  const identity = packageIdentityFromInput(input);
  if (identity) packageIdentities.set(identity.packageRoot, identity);
}
const packageMetadataList = [];
for (const identity of [...packageIdentities.values()].sort((a, b) => a.packageName.localeCompare(b.packageName))) {
  try {
    packageMetadataList.push(await packageMetadata(identity));
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Could not collect license for bundled package ${identity.packageName}: ${message}`);
  }
}
const licenseLines = [
  "# Bundled dependency licenses",
  "",
  "This file is generated by `npm run bundle`. It contains the license files shipped by the " +
  "npm packages represented in the esbuild bundle.",
  "License text is copied verbatim from each package; package metadata is included when a " +
  "package does not ship a standalone license file.",
  ""
];
for (const metadata of packageMetadataList) {
  licenseLines.push(`## ${metadata.packageName}@${metadata.version}`, "");
  if (metadata.licensePath && metadata.licenseText !== undefined) {
    const sourcePath = relative(root, metadata.licensePath).replaceAll("\\", "/");
    licenseLines.push(`Source: ${sourcePath}`, "", metadata.licenseText, "");
  } else {
    licenseLines.push(
      `No standalone license file was found. package.json license field: ${JSON.stringify(metadata.license)}.`,
      ""
    );
  }
}
await writeFile(licenseReport, `${licenseLines.join("\n")}\n`, "utf8");
console.log(`Bundled ${outfile}`);
